-- Part of a scheduled query (Ask Valerie Ong)

SELECT `ncr_report_order_booking`.`rdbms_id` AS `rdbms_id`,
  `ncr_report_order_booking`.`vendor_name` AS `vendor_name`,
  `ncr_report_order_booking`.`vendor_code` AS `vendor_code`,
  `ncr_report_order_booking`.`booking_id` AS `booking_id`,
  `ncr_report_order_booking`.`user` AS `user`,
  `ncr_report_order_booking`.`user_booked` AS `user_booked`,
  `ncr_report_order_booking`.`year_month` AS `year_month`,
  `ncr_report_order_booking`.`booking_date` AS `booking_date`,
  `ncr_report_order_booking`.`booking_yearweek` AS `booking_yearweek`,
  `ncr_report_order_booking`.`type` AS `type`,
  `ncr_report_order_booking`.`status` AS `status`,
  `ncr_report_order_booking`.`sold_price_local` AS `sold_price_local`,
  `ncr_report_order_booking`.`suggested_price_local` AS `suggested_price_local`,
  `ncr_report_order_booking`.`exchange_rate_value` AS `exchange_rate_value`,
  `ncr_report_order_booking`.`sold_price_eur` AS `sold_price_eur`,
  `ncr_report_order_booking`.`suggested_price_eur` AS `suggested_price_eur`,
  `ncr_report_order_booking`.`common_name` AS `common_name`,
  `ncr_report_order_booking`.`promo_areas_sold` AS `promo_areas_sold`,
  `ncr_report_order_booking`.`month_booked` AS `month_booked`,
  `ncr_report_order_booking`.`month` AS `month`,
  `ncr_report_order_booking`.`central` AS `central`,
  `ncr_report_order_booking`.`automated` AS `automated`,
  `ncr_report_order_booking`.`channel` AS `channel`,
  `ncr_report_order_booking`.`current_week` AS `current_week`,
  `ncr_report_order_booking`.`report_weeks` AS `report_weeks`,
  `ncr_report_order_booking`.`gmv_class` AS `gmv_class`,
  `ncr_report_order_booking`.`vendor_grade` AS `vendor_grade`,
  `ncr_report_order_booking`.`final_source` AS `final_source`
FROM `dhh---analytics-apac.pandata_ap_commercial`.`ncr_report_order_booking` `ncr_report_order_booking`
