-- Part of a scheduled query (Ask Valerie Ong)

SELECT `NCR_Tableau_CPC_updated1`.`global_entity_id` AS `global_entity_id`,
  `NCR_Tableau_CPC_updated1`.`country` AS `country__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`booking_id` AS `booking_id__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`gmv_class` AS `gmv_class__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`vendor_grade` AS `vendor_grade__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`vendor_name` AS `vendor_name__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`vendor_code` AS `vendor_code__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`chain_name` AS `chain_name__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`chain_code` AS `chain_code__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`city_name` AS `city_name__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`hurrier_zone` AS `hurrier_zone__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`user` AS `user__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`channel` AS `channel__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`final_source` AS `final_source__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`booking_week` AS `booking_week__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`booking_yearweek` AS `booking_yearweek__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`type` AS `type__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`status` AS `status__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`start_date` AS `start_date__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`end_date` AS `end_date__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`last_day` AS `last_day__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`datelive` AS `datelive`,
  `NCR_Tableau_CPC_updated1`.`month` AS `month__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`yearmonth_live` AS `yearmonth_live__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`promo_areas_booked` AS `promo_areas_booked__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`promo_areas_available` AS `promo_areas_available`,
  CAST(`NCR_Tableau_CPC_updated1`.`click_price_local` AS FLOAT64) AS `click_price_local__NCR_Tableau_CPC_updated1_`,
  CAST(`NCR_Tableau_CPC_updated1`.`budgeted_clicks` AS FLOAT64) AS `budgeted_clicks__NCR_Tableau_CPC_updated1_`,
  CAST(`NCR_Tableau_CPC_updated1`.`initial_budget_local` AS FLOAT64) AS `initial_budget_local__NCR_Tableau_CPC_updated1_`,
  CAST(`NCR_Tableau_CPC_updated1`.`initial_budget_eur` AS FLOAT64) AS `initial_budget_eur__NCR_Tableau_CPC_updated1_`,
  CAST(`NCR_Tableau_CPC_updated1`.`final_spent_clicks` AS FLOAT64) AS `final_spent_clicks__NCR_Tableau_CPC_updated1_`,
  CAST(`NCR_Tableau_CPC_updated1`.`exchange_rate` AS FLOAT64) AS `exchange_rate__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`active_areas` AS `active_areas__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`cpc_orders` AS `cpc_orders__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`spent_clicks` AS `spent_clicks__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`afv_eur` AS `afv_eur__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`afv_local` AS `afv_local__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`sum_gfv_eur` AS `sum_gfv_eur`,
  `NCR_Tableau_CPC_updated1`.`sum_gfv_local` AS `sum_gfv_local`,
  `NCR_Tableau_CPC_updated1`.`avg_open_hrs_per_day` AS `avg_open_hrs_per_day`,
  `NCR_Tableau_CPC_updated1`.`avg_rating_per_vendor` AS `avg_rating_per_vendor`,
  CAST(`NCR_Tableau_CPC_updated1`.`final_budgeted_clicks` AS FLOAT64) AS `final_budgeted_clicks__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`cpc_rev_local` AS `cpc_rev_local__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`cpc_rev_eur` AS `cpc_rev_eur__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`cpc_conversion` AS `cpc_conversion__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`utilization` AS `utilization__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`final_budget_local` AS `final_budget_local__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`final_budget_eur` AS `final_budget_eur__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`cpc_roi` AS `cpc_roi__NCR_Tableau_CPC_updated1_`,
  `NCR_Tableau_CPC_updated1`.`budget_over_gfv` AS `budget_over_gfv`
FROM `dhh---analytics-apac.pandata_ap_commercial`.`NCR_Tableau_CPC_updated` `NCR_Tableau_CPC_updated1`
