SELECT `NCR_Tableau_CPC_updated`.`global_entity_id` AS `global_entity_id`,
  `NCR_Tableau_CPC_updated`.`country` AS `country`,
  `NCR_Tableau_CPC_updated`.`booking_id` AS `booking_id`,
  `NCR_Tableau_CPC_updated`.`gmv_class` AS `gmv_class`,
  `NCR_Tableau_CPC_updated`.`vendor_grade` AS `vendor_grade`,
  `NCR_Tableau_CPC_updated`.`vendor_name` AS `vendor_name`,
  `NCR_Tableau_CPC_updated`.`vendor_code` AS `vendor_code`,
  `NCR_Tableau_CPC_updated`.`chain_name` AS `chain_name`,
  `NCR_Tableau_CPC_updated`.`chain_code` AS `chain_code`,
  `NCR_Tableau_CPC_updated`.`city_name` AS `city_name`,
  `NCR_Tableau_CPC_updated`.`hurrier_zone` AS `hurrier_zone`,
  `NCR_Tableau_CPC_updated`.`user` AS `user`,
  `NCR_Tableau_CPC_updated`.`channel` AS `channel`,
  `NCR_Tableau_CPC_updated`.`final_source` AS `final_source`,
  `NCR_Tableau_CPC_updated`.`booking_week` AS `booking_week`,
  `NCR_Tableau_CPC_updated`.`booking_yearweek` AS `booking_yearweek`,
  `NCR_Tableau_CPC_updated`.`type` AS `type`,
  `NCR_Tableau_CPC_updated`.`status` AS `status`,
  `NCR_Tableau_CPC_updated`.`start_date` AS `start_date`,
  `NCR_Tableau_CPC_updated`.`end_date` AS `end_date`,
  `NCR_Tableau_CPC_updated`.`last_day` AS `last_day`,
  `NCR_Tableau_CPC_updated`.`datelive` AS `datelive`,
  `NCR_Tableau_CPC_updated`.`month` AS `month`,
  `NCR_Tableau_CPC_updated`.`yearmonth_live` AS `yearmonth_live`,
  `NCR_Tableau_CPC_updated`.`promo_areas_booked` AS `promo_areas_booked`,
  `NCR_Tableau_CPC_updated`.`promo_areas_available` AS `promo_areas_available`,
  CAST(`NCR_Tableau_CPC_updated`.`click_price_local` AS FLOAT64) AS `click_price_local`,
  CAST(`NCR_Tableau_CPC_updated`.`budgeted_clicks` AS FLOAT64) AS `budgeted_clicks`,
  CAST(`NCR_Tableau_CPC_updated`.`initial_budget_local` AS FLOAT64) AS `initial_budget_local`,
  CAST(`NCR_Tableau_CPC_updated`.`initial_budget_eur` AS FLOAT64) AS `initial_budget_eur`,
  CAST(`NCR_Tableau_CPC_updated`.`final_spent_clicks` AS FLOAT64) AS `final_spent_clicks`,
  CAST(`NCR_Tableau_CPC_updated`.`exchange_rate` AS FLOAT64) AS `exchange_rate`,
  `NCR_Tableau_CPC_updated`.`active_areas` AS `active_areas`,
  `NCR_Tableau_CPC_updated`.`cpc_orders` AS `cpc_orders`,
  `NCR_Tableau_CPC_updated`.`spent_clicks` AS `spent_clicks`,
  `NCR_Tableau_CPC_updated`.`afv_eur` AS `afv_eur`,
  `NCR_Tableau_CPC_updated`.`afv_local` AS `afv_local`,
  `NCR_Tableau_CPC_updated`.`sum_gfv_eur` AS `sum_gfv_eur`,
  `NCR_Tableau_CPC_updated`.`sum_gfv_local` AS `sum_gfv_local`,
  `NCR_Tableau_CPC_updated`.`avg_open_hrs_per_day` AS `avg_open_hrs_per_day`,
  `NCR_Tableau_CPC_updated`.`avg_rating_per_vendor` AS `avg_rating_per_vendor`,
  CAST(`NCR_Tableau_CPC_updated`.`final_budgeted_clicks` AS FLOAT64) AS `final_budgeted_clicks`,
  `NCR_Tableau_CPC_updated`.`cpc_rev_local` AS `cpc_rev_local`,
  `NCR_Tableau_CPC_updated`.`cpc_rev_eur` AS `cpc_rev_eur`,
  `NCR_Tableau_CPC_updated`.`cpc_conversion` AS `cpc_conversion`,
  `NCR_Tableau_CPC_updated`.`utilization` AS `utilization`,
  `NCR_Tableau_CPC_updated`.`final_budget_local` AS `final_budget_local`,
  `NCR_Tableau_CPC_updated`.`final_budget_eur` AS `final_budget_eur`,
  `NCR_Tableau_CPC_updated`.`cpc_roi` AS `cpc_roi`,
  `NCR_Tableau_CPC_updated`.`budget_over_gfv` AS `budget_over_gfv`
FROM `dhh---analytics-apac.pandata_ap_commercial`.`NCR_Tableau_CPC_updated` `NCR_Tableau_CPC_updated`
